{"tag": "function", "depth": 1, "time": 1708218614.1176977, "data": {"name": "connect_device", "call_args": {"uri": "Android:///127.0.0.1:16448"}, "start_time": 1708218613.979573, "ret": "<Android '127.0.0.1:16448'>", "end_time": 1708218614.1176977}}
{"tag": "function", "depth": 2, "time": 1708218616.6959069, "data": {"name": "try_log_screen", "call_args": {"screen": null, "quality": null, "max_size": null}, "start_time": 1708218614.1799905, "ret": {"screen": "1708218616677.jpg", "resolution": [1080, 1920]}, "end_time": 1708218616.6959069}}
{"tag": "info", "depth": 1, "time": 1708218616.7027235, "data": {"name": "Final Error", "traceback": "Traceback (most recent call last):\n  File \"D:\\Program Files\\Python\\Python39\\lib\\site-packages\\airtest\\cli\\runner.py\", line 72, in runTest\n    exec(compile(code.encode(\"utf-8\"), pyfilepath, 'exec'), self.scope)\n  File \"D:\\Scripts\\Airtest\\jnt\\multi-device-runner\\jnt_102_OA.air\\jnt_102_OA.py\", line 9, in <module>\n    driver = WebChrome()\n  File \"D:\\Program Files\\Python\\Python39\\lib\\site-packages\\airtest_selenium\\proxy.py\", line 28, in __init__\n    super(WebChrome, self).__init__(chrome_options=chrome_options, executable_path=executable_path,\nTypeError: __init__() got an unexpected keyword argument 'chrome_options'\n"}}
